### PR TITLE
Issues, PRs & NuGet badges

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by tpetricek** [comment]
I guess we should also enable Travis build for this!
Also, @sergey-tihon can you please add @LukeAllen and me as maintainers?

Thanks!

**Comment by sergey-tihon** [comment]
Done. I cannot activate Travis for this project until you grant write access  to this project for @fsprojects/fsprojects-write group.

**Comment by tpetricek** [comment]
Thanks - I added FnuPlot to @fsprojects/fsprojects-write - let me know if it does not work.

**Comment by sergey-tihon** [comment]
Seems that only you can enable Travis for fsprojects repos =( here https://travis-ci.org/profile/fsprojects
image

**Comment by tpetricek** [comment]
That's silly - but not a big deal - enabled it!

**Comment by tpetricek** [comment]
OK - Added Travis badge too.

Although I moved all of them under the brief description - I think it looks much nicer this way (they nicely fit on a single line in the default GitHub layout and are not randomly scattered around the page).

**Comment by sergey-tihon** [comment]
Thank you. Position is up to you actually.
I prefer option when they are at the top of the page and nuget version near the project name, like here https://github.com/fsprojects/Cricket/ You can immediately see now active project and is it production ready or still in alpha/beta stage. When everything is in one line it harder to read (for me)

**Comment by tpetricek** [comment]
I completely understand the logic, but simply don't like how it looks :-)

**Pull request merged**
