### PR TITLE
Added series types to display any series as something other than lines

### PR DESCRIPTION
**Pull request by ChrisDobby**
Wanted to display functions as either points or impulses so have added a type of SeriesType and an optional parameter to specify this type when creating a series.

### CODE REVIEW

**Comment by tpetricek** [comment]
Very nice extension! Thanks for adding this :-).

I'm happy to merge this as it is, though it made me wonder about the best way to structure the `Series` overloads. I think what we have in FnuPlot (even before the change) is a bit unclear. There are two things for doing overloads:

 1. How is data specified (string, sequence of Y values, sequence of XY pairs, sequence of Time*Y pairs)
 2. What graphical representation you want to get (line, points, pulses)

In F# Charting, the (2) determines name (`Chart.Line`, `Chart.Points` etc.) and (1) is done via overloading (overloads take different types as the first argument). I guess this is quite nice design, though I'm open to alternatives.

In FnuPlot, we have a mix of both - `Series.Function` is named based on (1), but `Series.Histogram` is named based on (2). I think the inconsistency is a bit unfortunate.

I suggest that some future version of FnuPlot should probably restructure this and add a bit of consistency. I'd like to get your thoughts on this (and also @LukeAllen's).

Sorry for an off-topic rant :-). In any case, your change looks good - and is consistent with the current inconsistent state of things!

**Comment by ChrisDobby** [comment]
Yes I had originally wanted to use Series.Points, Series.Impulses but with there already being Series.Function, Series.XY etc that specify the data rather than the representation I stuck to keeping with the inconsistency!  I would think that the best way to do it would be as you suggest and to specify the data via overloading - I'm quite happy to make said change if it's decided to go ahead with it.

**Comment by LukeAllen** [comment]
Great extension! I think a restructuring to provide consistency makes sense. The library only has a few users right now, so I think it's ok to break backwards compatibility to make it better for the future.

**Comment by tpetricek** [comment]
Wonderful, I completely support restructuring!

I'm going to merge this PR as it is and release it as a new version - and if you can then put together a PR that does more restructuring (which would be amazing!), we can then increment the version from `0.0.7` to `0.1.0` to denote a bigger breaking change.

**Comment by tpetricek** [comment]
Available as 0.0.7-beta on NuGet :-). Thanks for the contribution!

**Comment by tpetricek** [comment]
BTW: @LukeAllen - what is your user name on NuGet, so that I can add you as a person who can release new versions of the package? (I'm happy to be involved in maintaining FnuPlot, but in case I'm somewhere and cannot reply soon enough, it would be great if someone else can do the release too!)

**Comment by LukeAllen** [comment]
@tpetricek I didn't have one, but I do now -- my username is LukeAllen

**Comment by tpetricek** [comment]
@LukeAllen Expect an email from NuGet soon!

**Pull request merged**
