### PR TITLE
typo

### PR DESCRIPTION
**Pull request by enricosada**
typo and newline at EOF

### CODE REVIEW

**Comment by LukeAllen** [comment]
Merged, thanks

**Comment by tpetricek** [comment]
Great to see this merged :-). 

@LukeAllen Did you have any chance to look into the release process?

**Comment by LukeAllen** [comment]
Yeah I've been learning it today. I hadn't used the FAKE build process before but I'm learning it (I'm having to learn how to update the docs, since they need to change to match the new functions.)

**Comment by tpetricek** [comment]
No problem :-) there is quite a lot of things going on in the build process. (The [ProjectScaffold](http://fsprojects.github.io/ProjectScaffold/) page is useful documentation.)

Let me know if you need any help!

**Comment by LukeAllen** [comment]
This is probably a noob question since I haven't used Fake before, but I'm having trouble with part of the build process - when I run "build GenerateHelp" (from Windows), the html files with embedded code all look good, except they have a couple pages of random code added below them. Here's an example:
https://www.dropbox.com/s/ob0s5fhocgeg6yg/Getting%20started%20with%20FnuPlot.html?dl=0

**Comment by tpetricek** [comment]
This is code that should be hidden by the CSS and is used in the tooltips. By default, the generated files should be pointing to the CSS on the web, so I'm not sure why this wouldn't be hidden.

When testing documentation, I also sometimes just go through the `generate.fsx` script in F# Interactive (and [there is an #if-ed code](https://github.com/fsprojects/FnuPlot/blob/master/docs/tools/generate.fsx#L46) that you can use to generate local CSS links).

**Comment by LukeAllen** [comment]
Ah you're right; the HTML uses a path to the CSS (/Fnuplot/content/style.css), which is different from its local location in the "output" folder (./content/style.css). I'll just continue and hopefully it will look right when uploaded. Thanks!

**Comment by LukeAllen** [comment]
Just published; the formatting looks good online. Thanks for showing me how to do it.

**Comment by tpetricek** [comment]
Fantastic, thanks!

**Pull request merged**
