### PR TITLE
Fix mono build

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Build fails on my system because of 3 reasons:

* F# interactive < `fsharp 4.1.18-1` fails on Mono 5: Fixed by updating dependencies
```
> [Loading /home/juergen/fsharp/FnuPlot/paket-files/fsharp/FAKE/modules/Octokit/Octokit.fsx
 Loading /home/juergen/fsharp/FnuPlot/build.fsx]
error FS0193: Specified method is not supported.
```
* Invalid case in filename (build.fsx) breaks build when using case-sensitive filesystem (GNU/Linux)
```
Could not find script 'packages/SourceLink.Fake/Tools/Fake.fsx' in any paths searched. Searched paths:
```
* Cant build on Mono 5 using `TargetFrameworkVersion` 4.0: Fixed by updating to 4.5
```
FSC: error FS0193: The module/namespace 'System.Collections.Generic' from compilation unit 'mscorlib' did not contain the namespace, module or type 'IReadOnlyCollection`1'
```

### CODE REVIEW

**Comment by LukeAllen** [comment]
@juergenhoetzel thank you for the PR. I've actually stopped using F#, and I don't have an F# build environment set up any more. Would you like to take ownership of FnuPlot? I can transfer the repository to you.

**Comment by juergenhoetzel** [comment]
@LukeAllen, I'm not sure If I will use `FnuPlot` in the long run: Right now I'm using it for a single project I'm working on.  But you might add me as a collaborator?

**Comment by LukeAllen** [comment]
Ok, you should have an invitation to be a collaborator.

**Comment by juergenhoetzel** [comment]
> Ok, you should have an invitation to be a collaborator.

Thanks!

**Pull request merged**
